nelmio_cors:
    defaults:
        allow_origin: ['https://localhost:8000', 'https://127.0.0.1:8000', 'https://localhost:8080']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://localhost:8000', 'https://127.0.0.1:8000', 'https://localhost:8080']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
