# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['https://127.0.0.1:8000', 'https://localhost:8000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
