# config/packages/web_profiler.yaml
web_profiler:
    toolbar: true
    intercept_redirects: false
    # Adăugați aceste linii
    excluded_ajax_paths: '^/api/'

framework:
    profiler:
        # Această opțiune este importantă pentru a colecta date
        collect: true
