# config/services.yaml
parameters:

services:
    # Configurația implicită pentru serviciile din *acest* fișier
    _defaults:
        autowire: true      # Injectează automat dependențele în servicii.
        autoconfigure: true # Înregistrează automat serviciile ca și comenzi, event subscribers etc.

    # Face clasele din src/ disponibile pentru a fi folosite ca servicii.
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php}'
